### ISSUE TITLE
Cannot install keyboard hook

### ISSUE THREAD

**Issue by ABS96** [OzymandiasTheGreat/macpy#1]
Using the method Keyboard.install_keyboard_hook() yields the following error:

```
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\macpy\interface\winkeyboard.py", line 119, in _hook
    windll.kernel32.GetModuleHandleW(None), 0)
ctypes.ArgumentError: argument 3: <class 'OverflowError'>: int too long to convert

Exception in thread WinKeyboard hook loop:
Traceback (most recent call last):
  File "C:\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python37\lib\site-packages\macpy\interface\winkeyboard.py", line 129, in _hook
    windll.user32.UnhookWindowsHookEx(hID)
UnboundLocalError: local variable 'hID' referenced before assignment
```

This is on Windows 10 build 1083.
I've read the docs, but couldn't figure out how to resolve this. Any ideas?

**Comment by OzymandiasTheGreat** [comment]
Can't reproduce so far.
Are you by any chance using 32bit version? That my explain the first (and main error) as `c_int` is 32bits on 32bit python, so too small to hold a 64bit handle.

**Comment by ABS96** [comment]
The version of Python that I'm using should be 64-bit, as `sys.maxsize` is [`9223372036854775807`](https://stackoverflow.com/a/1842699) and [my executables](https://superuser.com/a/889267) are also 64-bit.
However, my `c_int` _is_ only 32-bit.

```
>>> ctypes.c_int(2**30)
c_long(1073741824)
>>> ctypes.c_int(2**31)
c_long(-2147483648)
>>> ctypes.c_int(2**32)
c_long(0)
>>> ctypes.c_int(2**33)
c_long(0)
```

This might be an issue with [the way ctypes works](https://www.reddit.com/r/Python/comments/5v33e4/ctypes_incorrectly_guessing_type_sizes_of_64bit), but frankly, that's beyond my competence.

Maybe a package I'm using is configured wrong?

**Comment by OzymandiasTheGreat** [comment]
Honestly I have no clue here.
However, doing search and replace on `macpy\interface\winkeyboard.py` for `c_int` to `c_int64` should solve this.
That's what I'm gonna try once I get the time, however could you test this for now?

**Comment by ABS96** [comment]
Allright, I've tried `c_int64`, `c_uint64`, and `c_ulonglong`, but the error persists.

**Comment by OzymandiasTheGreat** [comment]
Hm, my bad. Been a while since I worked on this, forgot code structure.
Anyway try adding a line after line 116:
`windll.user32.SetWindowsHookExW.argtypes = (c_int, wintypes.HANDLE, wintypes.HMODULE, wintypes.DWORD)`

`SetWindowsHookExW` signature is unset currently, so ctypes assumes `c_int` for every arg which is too small to hold `HMODULE`. At least that's what I think.

If this doesn't work, I'm afraid I'm out of ideas for now.

**Comment by ABS96** [comment]
Nice, that did the trick.  
Thanks for your help!

I've created a pull request with your fix.

**Comment by OzymandiasTheGreat** [comment]
You're quite welcome!
Thanks for your patience and the pull request, I don't quite have the time to work on this myself right now.
